# fly.toml app configuration file generated for ride-finder on 2024-05-22T02:52:11+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ride-finder'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[env]
  RAILS_ENV = "production"

[build]

[deploy]
  release_command = './bin/rails db:migrate'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/'
