name: Deploy to Fly.io
on:
  push:
    branches:
      - main
    types:
      - closed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}