name: Run rspec and rubocop

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: appdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          GOOGLE_MAPS_API_KEY: test_key
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - postgresql_data:/var/lib/postgresql/data

    steps: # GitHubのリポジトリからコードを取得する。CI環境の初期値はコードが空の状態。
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 131.0.6778.85
          install-chromedriver: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Cache node modules # Nodeモジュールをキャッシュ
        uses: actions/cache@v4
        with:
          path: node_modules # キャッシュするディレクトリを指定
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }} # キャッシュのキーを指定
          restore-keys: |
            ${{ runner.os }}-node-  # 部分一致する最新のキャッシュを探します。

      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          yarn install --frozen-lockfile

      - name: Database create and migrate # データベースの作成とマイグレーションを実行
        run: |
          bundler exec rails db:create RAILS_ENV=test
          bundler exec rails db:migrate RAILS_ENV=test

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: Run rspec
        run: bundle exec rspec

      - name: Archive rspec result screenshots # RSpecに失敗した時のスクリーンショットを追加
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rspec result screenshots
          path: tmp/capybara/

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run rubocop
        run: bundle exec rubocop


